### ISSUE TITLE
Notarization

### ISSUE THREAD

**Issue by michelottiABV** [miyako/4d-plugin-svg-converter#2]
Hello,

We are trying to notarize our application with the svg-converter plugin. We only need the windows part of the plugin but we need to notarize our application on Mac. Is there something that needs to be done to make this work?

**Comment by miyako** [comment]
You need to understand how notarisation _should_ be done, and how the application build dialog of 4D cuts corners (or should I say, simplifies the process) to only address the most typical cases.

For a stronger solution you could look into https://github.com/miyako/4d-utility-build-application.

I don't understand why you don't need the plugin for Mac, maybe the server is Windows and the clients are not, maybe some of the clients are Windows. I also don't know whether you have enabled automatic client update or not; there is no reason to omit these kinds of information. The solution is different for each specific case:

* The server is Windows, none of the clients are Mac
* The server is Windows, some of the clients are Mac
* The server is Windows, all of the clients are Mac

The status of automatic client update also has an impact on your build process.

**Comment by michelottiABV** [comment]
Thank you for your reply. We have just tested your procedure and it works perfectly.

Why only the windows part: Simply because we are just using the plugin to convert an svg file to a single page pdf. On Mac, we use the 4D "convert picture" command which does the job.
